// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetCare.Infrastructure.Data;

#nullable disable

namespace PetCare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520112438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCare.Domain.Entities.AplicacaoVacina", b =>
                {
                    b.Property<int>("IdAplicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aplicacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAplicacao"));

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_aplicacao");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.Property<int>("IdVacina")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vacina");

                    b.HasKey("IdAplicacao");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdVacina");

                    b.ToTable("Aplicacao_vacina", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Clinica", b =>
                {
                    b.Property<int>("IdClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClinica"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdClinica");

                    b.ToTable("Clinica", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_consulta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_consulta");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdClinica");

                    b.HasIndex("IdPet");

                    b.ToTable("Consulta", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.HistoricoSaude", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_historico");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_registro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdPet");

                    b.ToTable("Historico_saude", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("especie");

                    b.Property<int>("IdTutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    b.Property<int?>("Idade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Raca")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("raca");

                    b.HasKey("IdPet");

                    b.HasIndex("IdTutor");

                    b.ToTable("Pet", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdTutor");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Vacina", b =>
                {
                    b.Property<int>("IdVacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vacina");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacina"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdVacina");

                    b.ToTable("Vacina", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.AplicacaoVacina", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("AplicacoesVacina")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Vacina", "Vacina")
                        .WithMany("AplicacoesVacina")
                        .HasForeignKey("IdVacina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Consultas")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.HistoricoSaude", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("HistoricosSaude")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.Navigation("AplicacoesVacina");

                    b.Navigation("Consultas");

                    b.Navigation("HistoricosSaude");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Vacina", b =>
                {
                    b.Navigation("AplicacoesVacina");
                });
#pragma warning restore 612, 618
        }
    }
}
